-- MySQL Script generated by MySQL Workbench
-- Sat Sep 23 20:11:36 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SISTEMADEVOTACION
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `SISTEMADEVOTACION` ;

-- -----------------------------------------------------
-- Schema SISTEMADEVOTACION
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SISTEMADEVOTACION` DEFAULT CHARACTER SET utf8 ;
USE `SISTEMADEVOTACION` ;

-- -----------------------------------------------------
-- Table `SISTEMADEVOTACION`.`CANDIDATO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SISTEMADEVOTACION`.`CANDIDATO` (
  `IdCandidato` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(450) NOT NULL,
  PRIMARY KEY (`IdCandidato`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SISTEMADEVOTACION`.`REGION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SISTEMADEVOTACION`.`REGION` (
  `IdRegion` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(450) NOT NULL,
  PRIMARY KEY (`IdRegion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SISTEMADEVOTACION`.`COMUNA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SISTEMADEVOTACION`.`COMUNA` (
  `IdComuna` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(450) NOT NULL,
  `IdRegion` INT NOT NULL,
  PRIMARY KEY (`IdComuna`),
  INDEX `fk_COMUNA_REGION1_idx` (`IdRegion` ASC) ,
  CONSTRAINT `fk_COMUNA_REGION1`
    FOREIGN KEY (`IdRegion`)
    REFERENCES `SISTEMADEVOTACION`.`REGION` (`IdRegion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SISTEMADEVOTACION`.`VOTACION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SISTEMADEVOTACION`.`VOTACION` (
  `Rut` VARCHAR(250) NOT NULL,
  `NombreCompleto` VARCHAR(450) NOT NULL,
  `Alias` VARCHAR(250) NOT NULL,
  `Email` VARCHAR(250) NOT NULL,
  `IdCandidato` INT NOT NULL,
  `IdComuna` INT NOT NULL,
  PRIMARY KEY (`Rut`),
  INDEX `fk_VOTACION_CANDIDATO1_idx` (`IdCandidato` ASC) ,
  INDEX `fk_VOTACION_COMUNA1_idx` (`IdComuna` ASC) ,
  CONSTRAINT `fk_VOTACION_CANDIDATO1`
    FOREIGN KEY (`IdCandidato`)
    REFERENCES `SISTEMADEVOTACION`.`CANDIDATO` (`IdCandidato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VOTACION_COMUNA1`
    FOREIGN KEY (`IdComuna`)
    REFERENCES `SISTEMADEVOTACION`.`COMUNA` (`IdComuna`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SISTEMADEVOTACION`.`MEDIODEINFORMACION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SISTEMADEVOTACION`.`MEDIODEINFORMACION` (
  `IdMedioDeInformacion` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(450) NOT NULL,
  `Rut` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`IdMedioDeInformacion`),
  INDEX `fk_MEDIODEINFORMACION_VOTACION1_idx` (`Rut` ASC) ,
  CONSTRAINT `fk_MEDIODEINFORMACION_VOTACION1`
    FOREIGN KEY (`Rut`)
    REFERENCES `SISTEMADEVOTACION`.`VOTACION` (`Rut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
